update debrfs

diff --git a/usr/bin/debrfs b/usr/bin/debrfs
--- a/usr/bin/debrfs
+++ b/usr/bin/debrfs
@@ -23,63 +23,47 @@
 #############################################################################################################################################################################
 
 
-# -- Run as root or ask user for sudo
-
+# -- Check if running with root privileges or ask for sudo.
 (( EUID != 0 )) && exec sudo -- "$0" "$@"
 
-
-# -- Define the path of the debrfs configuration file
-
+# -- Define the path of the debrfs configuration file.
 CONFIG_FILE=/etc/debrfs.conf
 
-
-# -- Load values from configuration file
-# -- Include fix for SC1090 – ShellCheck
-
-if [[ ! -f $CONFIG_FILE ]]; then
+# -- Load values from the configuration file.
+if [[ -f $CONFIG_FILE ]]; then
+    echo "Configuration file found! Loading..."
+    #shellcheck source=/dev/null
+    . "$CONFIG_FILE"
+else
     echo "Configuration file not found! Exiting..." 2>&1
     exit 1
-    else
-        echo "Configuration file found! Loading..."
-        # shellcheck source=/dev/null
-        . "$CONFIG_FILE"
 fi
 
-
-# -- Check if debootstrap is available, if not, install it
-
-PKG_OK=$(dpkg-query -W --showformat='${Status}\n' "$REQUIRED_PKG"|grep "install ok installed")
-
-echo Checking for "$REQUIRED_PKG": "$PKG_OK"
-
-if [ "" = "$PKG_OK" ]; then
+# -- Check if debootstrap is available, if not, install it.
+if ! dpkg -s "$REQUIRED_PKG" >/dev/null 2>&1; then
     echo "No $REQUIRED_PKG found. Installing $REQUIRED_PKG."
     apt -yy install --no-install-recommends "$REQUIRED_PKG"
-    else
-        echo "Unable to install $REQUIRED_PKG. Quitting."
+else
+    echo "Package $REQUIRED_PKG is already installed."
 fi
 
-
-# -- Create target directory for rootfs and use debootstrap to add content
-# -- Clean target directory if already present and add content
-
+# -- Create target directory for rootfs and use debootstrap to add content.
 if [[ ! -d $ROOTFS_DIR ]]; then
-    echo "Directory not found! Creating..." 2>&1
+    echo "Directory not found! Creating..."
     mkdir -p "$ROOTFS_DIR"
-    debootstrap --variant="$ROOTFS_VARIANT" --include="$ROOTFS_INCLUDE" --exclude="$ROOTFS_EXCLUDE" --arch "$ROOTFS_ARCH" --cache-dir=/tmp "$ROOTFS_SUITE" "$ROOTFS_DIR" "$ROOTFS_MIRROR"
-    else
-        echo "Directory found! Cleaning..."
-        rm -rf "$ROOTFS_DIR" && mkdir -p "$ROOTFS_DIR"
-        debootstrap --variant="$ROOTFS_VARIANT" --include="$ROOTFS_INCLUDE" --exclude="$ROOTFS_EXCLUDE" --arch "$ROOTFS_ARCH" --cache-dir=/tmp "$ROOTFS_SUITE" "$ROOTFS_DIR" "$ROOTFS_MIRROR"
+else
+    echo "Directory found! Cleaning..."
+    rm -rf "$ROOTFS_DIR" && mkdir -p "$ROOTFS_DIR"
 fi
 
+# -- Run debootstrap to populate the rootfs directory.
+debootstrap --variant="$ROOTFS_VARIANT" --include="$ROOTFS_INCLUDE" --exclude="$ROOTFS_EXCLUDE" --arch "$ROOTFS_ARCH" --cache-dir=/tmp "$ROOTFS_SUITE" "$ROOTFS_DIR" "$ROOTFS_MIRROR"
 
-# -- Compress rootfs directory using TAR and XZ
-
+# -- Compress rootfs directory using TAR and XZ.
 if [[ ! -f $TAR_FILE ]]; then
-    echo "File not found! Creating..." 2>&1
+    echo "File not found! Creating..."
     rm "$ROOTFS_DIR"/var/cache/apt/archives/*.deb && tar -I 'xz -9' -cvf "$TAR_FILE" --exclude="$ROOTFS_DIR/var/cache/apt/archives" -C "$ROOTFS_DIR" .
-    else
-        echo "File found! Cleaning..."
-        rm -rf "$TAR_FILE" && rm "$ROOTFS_DIR"/var/cache/apt/archives/*.deb && tar -I 'xz -9' -cvf "$TAR_FILE" --exclude="$ROOTFS_DIR/var/cache/apt/archives" -C "$ROOTFS_DIR" .
+else
+    echo "File found! Cleaning..."
+    rm -rf "$TAR_FILE" && rm "$ROOTFS_DIR"/var/cache/apt/archives/*.deb && tar -I 'xz -9' -cvf "$TAR_FILE" --exclude="$ROOTFS_DIR/var/cache/apt/archives" -C "$ROOTFS_DIR" .
 fi
