Update debrfs

diff --git a/usr/bin/debrfs b/usr/bin/debrfs
--- a/usr/bin/debrfs
+++ b/usr/bin/debrfs
@@ -29,25 +29,25 @@
 # -- Define the path of the debrfs configuration file.
 CONFIG_FILE=/etc/debrfs.conf
 
-# -- Load values from the configuration file.
+# -- Load values from the configuration file
 if [[ -f $CONFIG_FILE ]]; then
     echo "Configuration file found! Loading..."
-    #shellcheck source=/dev/null
+    # shellcheck source=/dev/null
     . "$CONFIG_FILE"
 else
-    echo "Configuration file not found! Exiting..." 2>&1
+    echo "Configuration file not found! Exiting..." >&2
     exit 1
 fi
 
-# -- Check if debootstrap is available, if not, install it.
+# -- Check if debootstrap is available, if not, install it
 if ! dpkg -s "$REQUIRED_PKG" >/dev/null 2>&1; then
-    echo "No $REQUIRED_PKG found. Installing $REQUIRED_PKG."
-    apt -yy install --no-install-recommends "$REQUIRED_PKG"
+    echo "No $REQUIRED_PKG found. Installing $REQUIRED_PKG..."
+    apt -y install --no-install-recommends "$REQUIRED_PKG"
 else
     echo "Package $REQUIRED_PKG is already installed."
 fi
 
-# -- Create target directory for rootfs and use debootstrap to add content.
+# -- Create target directory for rootfs and use debootstrap to add content
 if [[ ! -d $ROOTFS_DIR ]]; then
     echo "Directory not found! Creating..."
     mkdir -p "$ROOTFS_DIR"
@@ -56,14 +56,14 @@ else
     rm -rf "$ROOTFS_DIR" && mkdir -p "$ROOTFS_DIR"
 fi
 
-# -- Run debootstrap to populate the rootfs directory.
+# -- Run debootstrap to populate the rootfs directory
 debootstrap --variant="$ROOTFS_VARIANT" --include="$ROOTFS_INCLUDE" --exclude="$ROOTFS_EXCLUDE" --arch "$ROOTFS_ARCH" --cache-dir=/tmp "$ROOTFS_SUITE" "$ROOTFS_DIR" "$ROOTFS_MIRROR"
 
-# -- Compress rootfs directory using TAR and XZ.
-if [[ ! -f $TAR_FILE ]]; then
+# -- Compress rootfs directory using TAR and XZ
+if [[ ! -f "$TAR_FILE" ]]; then
     echo "File not found! Creating..."
-    rm "$ROOTFS_DIR"/var/cache/apt/archives/*.deb && tar -I 'xz -9' -cvf "$TAR_FILE" --exclude="$ROOTFS_DIR/var/cache/apt/archives" -C "$ROOTFS_DIR" .
+    (cd "$ROOTFS_DIR" && tar -I 'xz -9' -cvf "$TAR_FILE" --exclude="var/cache/apt/archives" .)
 else
     echo "File found! Cleaning..."
-    rm -rf "$TAR_FILE" && rm "$ROOTFS_DIR"/var/cache/apt/archives/*.deb && tar -I 'xz -9' -cvf "$TAR_FILE" --exclude="$ROOTFS_DIR/var/cache/apt/archives" -C "$ROOTFS_DIR" .
+    rm -rf "$TAR_FILE" && (cd "$ROOTFS_DIR" && tar -I 'xz -9' -cvf "$TAR_FILE" --exclude="var/cache/apt/archives" .)
 fi
